server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security?characterEncoding=UTF-8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  #配置mongodb
  data:
    mongodb:
      uri: mongodb://localhost:27017/blog
  redis:
    #redis服务器地址
    host: localhost
    #redis连接端口号
    port: 6379
    #redis连接密码
    #    password: 123456
    # Redis 数据库索引（默认为 0）
    database: 0
    #redis连接超时时间（毫秒）
    timeout: 18000
    lettuce:
      pool:
        # 连接池最小空闲连接
        min-idle: 1
        # 连接池最大空闲连接
        max-idle: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: -1
#  servlet:
#    multipart:
#      max-request-size: 1024MB
#      max-file-size: 1024MB

mybatis:
  #配置mapper
  mapperLocations: classpath:mapper/*.xml
  #配置实体类
  typeAliasesPackage: com.ase.springsecurity.entity
  #mybatis控制台打印SQL语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

jwt:
  secret: secret
  expiration: 7200000
  token: Authorization

# mongodb开启Debug模式
# MongoRepository
logging:
  #控制台日志配置
  #  pattern:
  #    console: "[%thread] %-5level %logger{36} - %msg%n"
  level:
    org:
      springframework:
        data:
          mongodb:
            repository: DEBUG
            core: DEBUG



# 配置pagehelper参数
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

file-save-path: D:/ideaWorkspace/UploadData/images/