package com.ase.springsecurity.entity;

import java.io.Serializable;
import java.util.Date;

public class Todo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.todo
     *
     * @mbggenerated
     */
    private String todo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.dateDay
     *
     * @mbggenerated
     */
    private Date dateday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.logic_remove
     *
     * @mbggenerated
     */
    private Integer logicRemove;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table todo
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.id
     *
     * @return the value of todo.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.id
     *
     * @param id the value for todo.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.todo
     *
     * @return the value of todo.todo
     *
     * @mbggenerated
     */
    public String getTodo() {
        return todo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.todo
     *
     * @param todo the value for todo.todo
     *
     * @mbggenerated
     */
    public void setTodo(String todo) {
        this.todo = todo == null ? null : todo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.status
     *
     * @return the value of todo.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.status
     *
     * @param status the value for todo.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.dateDay
     *
     * @return the value of todo.dateDay
     *
     * @mbggenerated
     */
    public Date getDateday() {
        return dateday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.dateDay
     *
     * @param dateday the value for todo.dateDay
     *
     * @mbggenerated
     */
    public void setDateday(Date dateday) {
        this.dateday = dateday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.logic_remove
     *
     * @return the value of todo.logic_remove
     *
     * @mbggenerated
     */
    public Integer getLogicRemove() {
        return logicRemove;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.logic_remove
     *
     * @param logicRemove the value for todo.logic_remove
     *
     * @mbggenerated
     */
    public void setLogicRemove(Integer logicRemove) {
        this.logicRemove = logicRemove;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", todo=").append(todo);
        sb.append(", status=").append(status);
        sb.append(", dateday=").append(dateday);
        sb.append(", logicRemove=").append(logicRemove);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}